name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment"
        required: true
        default: qa
        type: choice
        options:
          - dev
          - qa
          - staging
          - product

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build --tag playwright-tests:latest .

      - name: Run Playwright tests in Docker container
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment || 'qa' }}
        run: docker run --rm -v ${{ github.workspace }}/playwright-report:/usr/src/app/playwright-report --env ENVIRONMENT=${{ github.event.inputs.environment || 'qa' }} playwright-tests:latest
        continue-on-error: true # Continue even if there are test failures

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
